AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: lambda.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 10
      Architectures:
        - arm64
      Layers:
        - !Ref NodeModulesLayer # 레이어를 참조하여 연결
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{proxy+}
            Method: ANY

  NodeModulesLayer: # 레이어 정의
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NodeModulesLayer
      Description: "Layer containing node_modules"
      ContentUri: ./layer/node_modules/ # 레이어에 포함할 파일 경로
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: "MIT"

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'GET'"

Outputs:
  ApiUrl:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
