AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi # HTTP API를 명시적으로 참조
            Path: /{proxy+} # 모든 경로를 Lambda로 전달합니다.
            Method: ANY # 모든 HTTP 메서드를 허용합니다.

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'GET'"

Outputs:
  ApiUrl:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
